### ISSUE TITLE
Allow to load evaluation data files from bmlab

### ISSUE THREAD

**Issue by raimund-schluessler** [GuckLab/impose#18]
An example file can be found here:
https://sharing.biotec.tu-dresden.de/index.php/s/ogrB3rmg1mvMNFg

The interesting data is in `/session/evaluation_models/<repetitionNumber>/results/` with `<repetitionNumber>` being the number of the current repetition, e.g. `0`.

The Brillouin datasets in this path are six dimensional matrices with the dimensions
- 1-3: being the spatial dimensions `x, y, z`
- 4: is the number of images taken at a spatial position
- 5: is the number of Brillouin regions to evaluate
- 6: is the number of peaks fitted per region
See https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/models/evaluation_model.py#L53-L60

**Comment by paulmueller** [comment]
Is there code in bmlab that I build on for this?

**Comment by raimund-schluessler** [comment]
> Is there code in bmlab that I can build on for this?

The data is in the evaluation model https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/models/evaluation_model.py which is then serialized. So there is not really *a* piece of code creating this file/data. But looking at the model should give a proper idea of the data structure.

**Comment by paulmueller** [comment]
Hi, sorry. I cannot access the file anymore. Could you please attach one as a zip file to this issue?

**Comment by raimund-schluessler** [comment]
Requires https://github.com/BrillouinMicroscopy/bmlab/pull/70.

**Comment by paulmueller** [comment]
@raimund-schluessler I am currently implementing a test for #22. Could you please provide me with a valid data file that contains actual data? The files from the bmlab/tests/data directory seem to only contain meta data.
