### ISSUE TITLE
Improve speed for large masks

### ISSUE THREAD

**Issue by paulmueller** [GuckLab/impose#59]
When masks are of great detail it becomes a bit of a hassle to manipulate their position and orientation. Often times only the knobs function and make it quite slow. Is there any way to make that more smooth/speed it up?

**Comment by paulmueller** [comment]
@StephanieMoe This is fixed in 0.4.3, albeit there is no macOS installer anymore, so you have to install via `pip install --upgrade impose`.

**Comment by StephanieMoe** [comment]
Great. Thanks. I will have a look. The new installation should be no problem.
